# Generated by Django 3.1.3 on 2020-11-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=12)),
                ('availability', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.CharField(default='Not Assigned', max_length=150)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=60)),
                ('customer_name', models.CharField(max_length=70)),
                ('item_count', models.IntegerField(default=0)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
