# Generated by Django 2.2 on 2020-11-11 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerceweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
