# Generated by Django 3.1.2 on 2020-11-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerceweb', '0002_remove_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_imageUrl',
            field=models.TextField(default=999),
            preserve_default=False,
        ),
    ]
