# Generated by Django 3.1.2 on 2020-11-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerceweb', '0003_auto_20201130_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=999),
            preserve_default=False,
        ),
    ]
