# Generated by Django 3.1.3 on 2020-12-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerceweb', '0004_product_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FilePathField(path='/img')),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=12)),
                ('availability', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.CharField(default='Not Assigned', max_length=150)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
        migrations.CreateModel(
            name='Eli_Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
        migrations.CreateModel(
            name='Eli_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=60)),
                ('customer_name', models.CharField(max_length=70)),
                ('item_count', models.IntegerField(default=0)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
